sudo: required
dist: trusty
language: python
cache:
  - apt
  - pip

python:
  - 3.5
  - 3.6

install:
  - pip install pip --upgrade
  - easy_install distribute
  - pip install -r dev_requirements.txt

script:
  - python setup.py test
  - python setup.py sdist bdist bdist_wheel

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: iwqThAWvFHZgT9/5Gd65nMf1VT+rKuqPTbO/wzt6VDP8ev/QzGPr2oQTBvS7+VPfpXt3aEfFkx7ayUhKaqJWeBFh8SOv0Fg8VdrXK1yv0SrkX1c+7hTX3ExYE6GF1cCFqEGNdd/Zg2JcOxVPG8qgLF4uTDHrCBO+HMwQM+XkFmZXaDjsY4dkK9vyfKJ2t0L67QmVY1wbshUowf9ZyZP8KdMuWlPFU1murLXovA9QyKOfX5DmtkzDxTpZpu31ynfMk3n+ejboU4A4z+MIqEZOaRRwTu35wHSdj2NKYG66H/0Kmn1k/LRip8SbGPr53jBNBXyGGENHfg7pfBmsNWuyDlOjdWspg1M8VGnrfWOGtBK/jWRRbrQWcSa2txdstvoGh/zfJPIq77ToARXsWCE2W2LlPeoZoGIrhHUf/6pXnky+TzP3UJeLo0xXy19J4Dn60WF+j9A5S/Nkh3+kZGUNmCRuiHVE3wleFp9w1XIRaWFOt7HGJzyHMuY8WOWI9i4rs6HeS6YYUgs62teTgEtzzI+pFzcjO2kUMn2KObVLjnn3wCGyJSbWoYmwp+avD5SFPuFXfxr4dl5e1U63fES2lfqJ4b7I6pfQVJZDDNNNLYxLFxZYdP0CD7tjIQYSB55GJKn1qEhAxugz94SryJvLje7ignoVueHy1bBesbSrLiY=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
